// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package partials

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Menubar(fromProtected bool, username string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<nav class=\"navbar-container flex items-center justify-between\"><!-- Logo Section --><div class=\"logo\"><a class=\"btn btn-ghost text-xl\" href=\"/\">East West Furniture</a></div><!-- Menu Section --><div class=\"navbar-menu flex-1 flex justify-center\"><a class=\"p-4 hover:scale-[1.1]\" href=\"/inventory/inventorylist\">Inventory</a> <a class=\"p-4 hover:scale-[1.1]\" href=\"/products/productlist\">Product</a> <a class=\"p-4 hover:scale-[1.1]\" href=\"/invoices/invoicelist\">Invoice</a> <a class=\"p-4 hover:scale-[1.1]\" href=\"/shipments/shipmentlist\">Shipment</a> <a class=\"p-4 hover:scale-[1.1]\" href=\"/customers/customerlist\">Customer</a></div><!-- User Section --><div class=\"navbar-end flex items-center\"><!-- Username Display --><!-- Logout Button --><button hx-swap=\"transition:true\" hx-post=\"/inventory/logout\" hx-confirm=\"Are you sure you want to log out?\" class=\"btn btn-ghost text-lg\">Logout</button></div></nav>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
