// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package partials

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Navbar(fromProtected bool, username string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<nav class=\"navbar-container flex items-center justify-between\"><div class=\"logo\"><a hx-swap=\"transition:true\" class=\"btn btn-ghost text-xl\" href=\"/\">East West Furniture</a></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if fromProtected {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"navbar-menu flex-1 flex justify-center\"><a hx-swap=\"transition:true\" class=\"p-4 hover:scale-[1.1]\" href=\"/inventory/inventorylist\">Inventory</a> <a hx-swap=\"transition:true\" class=\"p-4 hover:scale-[1.1]\" href=\"/todo/product\">Product</a> <a hx-swap=\"transition:true\" class=\"p-4 hover:scale-[1.1]\" href=\"/todo/product\">Invoice</a> <a hx-swap=\"transition:true\" class=\"p-4 hover:scale-[1.1]\" href=\"/todo/product\">Shipment</a> <a hx-swap=\"transition:true\" class=\"p-4 hover:scale-[1.1]\" href=\"/todo/product\">Customer</a></div><div class=\"navbar-end flex items-center\"><span class=\"text-xl px-4\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(username)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/partials/navbar_partial.templ`, Line: 30, Col: 41}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</span> <button hx-swap=\"transition:true\" hx-post=\"/todo/logout\" hx-confirm=\"Are you sure you want to log out?\" onClick=\"this.addEventListener(&#39;htmx:confirm&#39;, (e) =&gt; {\r\n\t\t\t\t\t\te.preventDefault()\r\n\t\t\t\t\t\tSwal.fire({\r\n\t\t\t\t\t\t\ttitle: &#39;Do you want to perform this action?&#39;,\r\n\t\t\t\t\t\t\ttext: `${e.detail.question}`,\r\n\t\t\t\t\t\t\ticon: &#39;warning&#39;,\r\n\t\t\t\t\t\t\tbackground: &#39;#1D232A&#39;,\r\n\t\t\t\t\t\t\tcolor: &#39;#A6ADBA&#39;,\r\n\t\t\t\t\t\t\tshowCancelButton: true,\r\n\t\t\t\t\t\t\tconfirmButtonColor: &#39;#3085d6&#39;,\r\n\t\t\t\t\t\t\tcancelButtonColor: &#39;#d33&#39;,\r\n\t\t\t\t\t\t\tconfirmButtonText: &#39;Yes&#39;\r\n\t\t\t\t\t\t}).then((result) =&gt; {\r\n\t\t\t\t\t\t\tif(result.isConfirmed) e.detail.issueRequest(true);\r\n\t\t\t\t\t\t})\r\n\t\t\t\t\t})\" hx-target=\"body\" hx-push-url=\"true\" class=\"btn btn-ghost text-lg\">Logout</button></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"justify-end flex items-center\"><a hx-swap=\"transition:true\" class=\"btn btn-ghost text-lg px-4\" href=\"/register\">Register</a> <a hx-swap=\"transition:true\" class=\"btn btn-ghost text-lg px-4\" href=\"/login\">Login</a></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</nav>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
